name: Restrict PR to main

on:
  pull_request:
    branches: [main]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block PRs not from develop or hotfix
        if: ${{ !startsWith(github.head_ref, 'develop') && !startsWith(github.head_ref, 'hotfix/') }}
        run: |
          echo "Error: Only PRs from 'develop*' or 'hotfix/*' branches are allowed to merge into 'main'."
          exit 1